/**
 * Change requests (EPIC #52), stage 3: apply a validated delta. Everything that CAN be
 * deterministic is: the spec/PRD artifact updates are pure functions, property tests for
 * touched requirements are dropped/regenerated by id, and the regeneration SCOPE comes from
 * the blast radius — only generation itself (writing the changed code) is the model's job.
 * The full gate line then runs unchanged: scope narrows what's REGENERATED, never what's
 * VERIFIED.
 */
import { readFileSync, existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import type { Spec } from "../spec/index.ts";
import type { Prd, Requirement } from "../prd/index.ts";
import type { ChangeDelta } from "./delta.ts";
import type { BlastRadius } from "./blast.ts";
import { PROPTEST_DIR, propTestFileName } from "../proptest/validate.ts";

/** Pure: the spec's feature list after the delta. Modified features keep their name — the
 *  change lives in the PRD requirement and the regeneration brief. */
export function applyDeltaToSpec(spec: Spec, delta: ChangeDelta): Spec {
  const removed = new Set(delta.remove);
  return { ...spec, features: [...spec.features.filter((f) => !removed.has(f)), ...delta.add.map((a) => a.feature)] };
}

/** The next free F<n> id given existing requirements. */
export function nextRequirementId(reqs: Requirement[]): string {
  let max = 0;
  for (const r of reqs) {
    const m = /^F(\d+)$/.exec(r.id);
    if (m) max = Math.max(max, Number(m[1]));
  }
  return `F${max + 1}`;
}

/** Pure: the PRD's requirements after the delta — removed features drop their requirement,
 *  modified ones get the change appended (and acceptance replaced when the delta redefines
 *  it), added ones become new MVP requirements carrying the delta's acceptance criteria. */
export function applyDeltaToPrd(prd: Prd, delta: ChangeDelta): Prd {
  const removed = new Set(delta.remove);
  const byFeature = new Map(delta.modify.map((m) => [m.feature, m]));
  let requirements = prd.requirements.filter((r) => !removed.has(r.feature));
  requirements = requirements.map((r) => {
    const mod = byFeature.get(r.feature);
    if (!mod) return r;
    return { ...r, detail: `${r.detail} — CHANGED: ${mod.change}`, ...(mod.acceptance?.length ? { acceptance: mod.acceptance } : {}) };
  });
  const additions: Requirement[] = [];
  for (const a of delta.add) {
    // Next id over the ORIGINAL requirements too — a removed feature's id is never reused
    // (its dropped property-test file and journal entries still reference it).
    additions.push({ id: nextRequirementId([...prd.requirements, ...additions]), feature: a.feature, detail: `Added by change request: ${delta.summary || delta.request}`, acceptance: a.acceptance, priority: "MVP", scenarioRefs: [] });
  }
  return { ...prd, requirements: [...requirements, ...additions] };
}

/** The requirement ids whose property tests must be dropped before regeneration: a removed
 *  feature's test asserts behavior that should no longer exist; a modified one's may assert
 *  the OLD definition of correct. Dropping happens HERE — in the change flow, before the
 *  autofix loop's anti-tamper baseline is captured — so it is legitimate; the same deletion
 *  by the fixer mid-loop stays a rejected tamper. */
export function staleRequirementIds(prd: Prd, delta: ChangeDelta): string[] {
  const touched = new Set([...delta.remove, ...delta.modify.map((m) => m.feature)]);
  return prd.requirements.filter((r) => touched.has(r.feature)).map((r) => r.id);
}

export function dropPropertyTests(target: string, requirementIds: string[]): string[] {
  const dropped: string[] = [];
  for (const id of requirementIds) {
    const rel = join(PROPTEST_DIR, propTestFileName(id));
    if (existsSync(join(target, rel))) {
      rmSync(join(target, rel), { force: true });
      dropped.push(rel);
    }
  }
  return dropped;
}

/** The scoped regeneration brief. The model sees the delta, the blast radius, and the CURRENT
 *  content of every affected file; it may only output changed/new files as bolt actions. */
export function buildChangeBrief(target: string, delta: ChangeDelta, blast: BlastRadius, cap = 100_000): string {
  const lines: string[] = [
    `This is a CHANGE REQUEST against an existing, working, deployed app — not a fresh build.`,
    `Make the smallest correct change. Output ONLY the files you change or add, as bolt file actions`,
    `(<boltArtifact> with <boltAction type="file" filePath="...">). Never regenerate unrelated files;`,
    `never touch supabase/migrations that already exist (add a NEW migration if the schema must change);`,
    `never edit anything under tests/properties/.`,
    ``,
    `Customer request: ${delta.request}`,
    `Understood as: ${delta.summary}`,
  ];
  if (delta.add.length) {
    lines.push(``, `ADD:`);
    for (const a of delta.add) lines.push(`- ${a.feature}`, ...a.acceptance.map((c) => `    must satisfy: ${c}`));
  }
  if (delta.modify.length) {
    lines.push(``, `MODIFY:`);
    for (const m of delta.modify) lines.push(`- ${m.feature} → ${m.change}`);
  }
  if (delta.remove.length) {
    lines.push(``, `REMOVE (delete the feature's UI/routes; keep unrelated code and all existing migrations):`);
    for (const r of delta.remove) lines.push(`- ${r}`);
  }
  if (blast.unmapped.length) lines.push(``, `Note: ${blast.unmapped.join(", ")} map(s) to no existing component — place new code where the current structure suggests.`);
  lines.push(``, `Current content of the affected files (the change scope):`);
  let total = 0;
  for (const rel of blast.files) {
    if (total >= cap) break;
    try {
      const content = readFileSync(join(target, rel), "utf8");
      total += content.length;
      lines.push(`\n--- ${rel} ---\n${content}`);
    } catch {
      lines.push(`\n--- ${rel} --- (listed in the architecture but not on disk)`);
    }
  }
  return lines.join("\n");
}
